# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 110a0bf52f68199af77df04a6c45f976151759af59911bfda7cfa8663b8b3268d6b2705fb6dfa03f7dc2e4d62493cffee4244d939dc163b4e47f4079918f3f76
  foursquare_id: VHGHK0VXXDTZU5C3Y3VIFEDMUE2YRR2J2QLQRZPZ5EHX24VO
  foursquare_secret: 3PG2DSPCZYIO3C1EVKZ3HEPK40O5BZMN0G4QCPMWMQ3TZEKS

test:
  secret_key_base: 0564abaf6fd056718f37355962dd52264b556cbdfac587eb33dbdf017b14a2f9eafadeb20134f6f0e1c4945f6b637e63af721ebe43f9fc8434bc81553a10027d
  foursquare_id: VHGHK0VXXDTZU5C3Y3VIFEDMUE2YRR2J2QLQRZPZ5EHX24VO
  foursquare_secret: 3PG2DSPCZYIO3C1EVKZ3HEPK40O5BZMN0G4QCPMWMQ3TZEKS

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  foursquare_id: VHGHK0VXXDTZU5C3Y3VIFEDMUE2YRR2J2QLQRZPZ5EHX24VO
  foursquare_secret: 3PG2DSPCZYIO3C1EVKZ3HEPK40O5BZMN0G4QCPMWMQ3TZEKS
